Repository aemsites/vg-macktrucks-com, pull requests merged in 2024-11, with the labels that each got.

#27 Block Library config updated #26
  .github/pull_request_template.md
  tools/sidekick/config.json
  tools/sidekick/library.css
  tools/sidekick/library.html
  tools/sidekick/library.js
Labels: NFR

#31 Release 29
  .github/ISSUE_TEMPLATE/new_feature.yml
  .github/pull_request_template.md
  blocks/v2-stories-carousel/v2-stories-carousel.css
  blocks/v2-stories-carousel/v2-stories-carousel.js
  icons/chevron-left-thin.svg
  icons/chevron-right-thin.svg
  package-lock.json
  package.json
  tools/sidekick/config.json
  tools/sidekick/library.css
  tools/sidekick/library.html
  tools/sidekick/library.js
Labels: Ignore for release

#103 Template: Bulldog Magazine Article #88
  blocks/v2-hero/v2-hero.css
  blocks/v2-image-banner/v2-image-banner.css
  blocks/v2-recommendations/v2-recommendations.css
  blocks/v2-recommendations/v2-recommendations.js
  blocks/v2-social-block/v2-social-block.css
  blocks/v2-social-block/v2-social-block.js
  templates/v2-magazine/v2-magazine.css
Labels: FR

#105 Fix v2 category collage #13
  README.md
  blocks/v2-category-collage/v2-category-collage.js
Labels: Bugfix

#108 Fix v2 navigation hub #16
  blocks/v2-navigation-hub/v2-navigation-hub.css
Labels: Bugfix

#110 Fix v2 cards #17
  blocks/v2-cards/v2-cards.css
Labels: Bugfix

#111 Fix v2-columns #19
  blocks/v2-columns/v2-columns.css
  blocks/v2-columns/v2-columns.js
Labels: Bugfix

#112 Fix v2 magazine tab #15
  blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.css
Labels: Bugfix
