Repository aemsites/vg-macktrucks-com, pull requests merged in 2025-01, with the labels that each got.

#155 superscript enhancement in v2-tabbed-carousel #69
  blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
  blocks/v2-tabbed-carousel/v2-tabbed-carousel.js
Labels: FR

#153 V2 Explore magazine filters block #41
  blocks/v2-explore-articles/v2-explore-articles.css
  blocks/v2-explore-articles/v2-explore-articles.js
  icons/chevron-down-thin.svg
  icons/close-thin.svg
  icons/close.svg
  icons/filter-settings.svg
  icons/tick.svg
  placeholder.json
  scripts/services/magazine.service.js
  styles/styles.css
Labels: FR

#158 Release 32
  blocks/v2-explore-articles/v2-explore-articles.css
  blocks/v2-explore-articles/v2-explore-articles.js
  blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
  blocks/v2-tabbed-carousel/v2-tabbed-carousel.js
  icons/chevron-down-thin.svg
  icons/close-thin.svg
  icons/close.svg
  icons/filter-settings.svg
  icons/tick.svg
  package-lock.json
  package.json
  placeholder.json
  scripts/services/magazine.service.js
  styles/styles.css
Labels: Ignore for release

#157 Remove Global Scroll-to-Top Button from Website #48
  blocks/dealer-locator/dealer-locator.css
  blocks/footer/footer.css
  blocks/footer/footer.js
  blocks/hotspots/hotspots.css
  blocks/v2-dealer-locator/v2-dealer-locator.css
Labels: FR

#162 Countdown in hero (1 of 3) #133
  blocks/v2-hero/v2-hero.css
  blocks/v2-hero/v2-hero.js
  common/countdown/countdown.css
  common/countdown/countdown.js
  fonts/digital-display-tfb.ttf
  scripts/common.js
  styles/lazy-styles.css
  styles/styles.css
Labels: FR

#164 CR: Inter Font Enhancements #151
  blocks/header/header.css
  blocks/performance-specifications/performance-specifications.css
  blocks/v2-accordion-column/v2-accordion-column.css
  blocks/v2-accordion/v2-accordion.css
  blocks/v2-cards/v2-cards.css
  blocks/v2-columns/v2-columns.css
  blocks/v2-hero/v2-hero.css
  blocks/v2-hotspots/v2-hotspots.css
  blocks/v2-icon-cards/v2-icon-cards.css
  blocks/v2-images-grid/v2-images-grid.css
  blocks/v2-inpage-navigation/v2-inpage-navigation.css
  blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.css
  blocks/v2-newsletter/v2-newsletter.css
  blocks/v2-pencil-promo/v2-pencil-promo.css
  blocks/v2-product-listing/v2-product-listing.css
  blocks/v2-social-block/v2-social-block.css
  blocks/v2-specifications/v2-specifications.css
  blocks/v2-sub-navigation/v2-sub-navigation.css
  blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
  blocks/v2-testimonial/v2-testimonial.css
  blocks/v2-truck-builder/v2-truck-builder.css
  blocks/v2-truck-lineup/v2-truck-lineup.css
  styles/styles.css
Labels: Change Request

#169 Release 33
  404.html
  blocks/dealer-locator/dealer-locator.css
  blocks/footer/footer.css
  blocks/footer/footer.js
  blocks/header/header.css
  blocks/hotspots/hotspots.css
  blocks/performance-specifications/performance-specifications.css
  blocks/v2-accordion-column/v2-accordion-column.css
  blocks/v2-accordion/v2-accordion.css
  blocks/v2-cards/v2-cards.css
  blocks/v2-columns/v2-columns.css
  blocks/v2-dealer-locator/v2-dealer-locator.css
  blocks/v2-dealer-locator/versions/default/sidebar-maps.js
  blocks/v2-dealer-locator/versions/export/sidebar-maps.js
  blocks/v2-hero/v2-hero.css
  blocks/v2-hero/v2-hero.js
  blocks/v2-hotspots/v2-hotspots.css
  blocks/v2-icon-cards/v2-icon-cards.css
  blocks/v2-images-grid/v2-images-grid.css
  blocks/v2-inpage-navigation/v2-inpage-navigation.css
  blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.css
  blocks/v2-newsletter/v2-newsletter.css
  blocks/v2-pencil-promo/v2-pencil-promo.css
  blocks/v2-product-listing/v2-product-listing.css
  blocks/v2-social-block/v2-social-block.css
  blocks/v2-specifications/v2-specifications.css
  blocks/v2-sub-navigation/v2-sub-navigation.css
  blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
  blocks/v2-testimonial/v2-testimonial.css
  blocks/v2-truck-builder/v2-truck-builder.css
  blocks/v2-truck-lineup/v2-truck-lineup.css
  common/countdown/countdown.css
  common/countdown/countdown.js
  fonts/digital-display-tfb.ttf
  package-lock.json
  package.json
  scripts/common.js
  styles/lazy-styles.css
  styles/styles.css
Labels: Ignore for release
