Repository aemsites/vg-macktrucks-com, pull requests merged in 2025-05, with the labels that each got.

#304 Release 40
  blocks/explore-articles/explore-articles.js
  blocks/header/header.js
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
  blocks/v2-dealer-locator/shared/template.js
  blocks/v2-dealer-locator/v2-dealer-locator.css
  blocks/v2-dealer-locator/v2-dealer-locator.js
  blocks/v2-dealer-locator/versions/default/sidebar-maps.js
  blocks/v2-dealer-locator/versions/export/sidebar-maps.js
  common/custom-dropdown/custom-dropdown.css
  package-lock.json
  package.json
  scripts/search-api.js
  scripts/services/magazine.service.js
  styles/styles.css
Labels: Ignore for release

#306 Bug: form link is used as title #305
  blocks/v2-custom-form/v2-custom-form.js
Labels: Bugfix

#303 Bug: white close button on header in search page at mobile viewport #286
  blocks/header/header.css
Labels: Bugfix

#312 NFR: Language setting needs to be applied to all website - MT #100
  scripts/scripts.js
Labels: NFR

#313 FR: Add honeypot field to V2 Custom Form block detect bot submission #308
  blocks/v2-custom-form/v2-custom-form.js
  styles/styles.css
Labels: FR

#315 FR: Dropdown for state selection in V2 Custom Form - MT #309
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
  common/custom-dropdown/custom-dropdown.css
Labels: FR

#316 FR: Add Radio buttons to the V2 Custom Form block - MT #302
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
  common/custom-dropdown/custom-dropdown.css
Labels: FR

#329 FR: v2-custom-form don't send on submit the hidden fields that are dependent on another input field value #328
  blocks/v2-custom-form/v2-custom-form.js
Labels: FR

#327 NFR: Improve the loading of AEM asset videos and the Video.js library #263
  scripts/delayed.js
  scripts/scripts.js
  scripts/video-helper.js
Labels: NFR

#330 FR: Add vertical margins to v2 icon cards row #318
  blocks/v2-icon-cards/v2-icon-cards.css
Labels: FR

#331 Release 41
  blocks/header/header.css
  blocks/header/header.js
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
  blocks/v2-dealer-locator/versions/default/sidebar-maps.js
  blocks/v2-icon-cards/v2-icon-cards.css
  blocks/v2-specifications/v2-specifications.js
  blocks/v2-truck-lineup/v2-truck-lineup.js
  common/custom-dropdown/custom-dropdown.css
  package-lock.json
  package.json
  scripts/common.js
  scripts/delayed.js
  scripts/scripts.js
  scripts/video-helper.js
  styles/styles.css
Labels: Ignore for release

#324 FR: Chart engine for the Performance Specifications block #240
  blocks/performance-specifications/performance-specifications.css
  blocks/performance-specifications/performance-specifications.js
  styles/styles.css
Labels: FR

#334 FR: V2 Feature Carousel - Add capability to use background video #321
  blocks/v2-feature-carousel/v2-feature-carousel.css
  blocks/v2-feature-carousel/v2-feature-carousel.js
  scripts/video-helper.js
Labels: FR

#335 FR: V2 Hero create new variant for secondary PDP #91
  blocks/v2-hero/v2-hero.css
  blocks/v2-hero/v2-hero.js
  styles/styles.css
Labels: FR

#336 FR: Add Custom Mute/Unmute button #310
  blocks/v2-columns/v2-columns.js
  blocks/v2-embed/v2-embed.js
  blocks/v2-video/v2-video.js
  common/modal/modal-component.css
  common/modal/modal-component.js
  icons/muted.svg
  icons/unmuted.svg
  placeholder.json
  scripts/video-helper.js
  styles/styles.css
  test/scripts/video-helper.test.js
Labels: FR

#333 FR: Menu (tabs-with-cards, featured-card) - Need ability for mega menu to feature one or two trucks #319
  blocks/header/header.css
  blocks/header/header.js
  icons/mute-button.svg
Labels: FR

#338 FR: Mega menu height needs to expand based on content #194
  blocks/header/header.css
  blocks/header/header.js
  blocks/sub-nav/sub-nav.css
  blocks/v2-inpage-navigation/v2-inpage-navigation.css
  blocks/v2-truck-lineup/v2-truck-lineup.css
  styles/styles.css
Labels: FR
