Repository aemsites/vg-macktrucks-com, pull requests merged in 2025-06, with the labels that each got.

#350 FR: Enhance/style videojs big play button #346 #347
  styles/styles.css
Labels: FR

#349 Bug: Megamenu featured card content missing #344
  blocks/header/header.css
Labels: Bugfix

#351 Bug: Cookie banner fails to render correctly when opening video in modal #337
  common/modal/modal-component.css
  styles/styles.css
Labels: Bugfix

#360 FR: Mobile Trucks lineup carousel enhancement #90
  blocks/v2-truck-lineup/v2-truck-lineup.css
  blocks/v2-truck-lineup/v2-truck-lineup.js
Labels: FR

#361 Bug: Fixed background colour for Video mute and play buttons
  icons/muted.svg
  icons/unmuted.svg
  styles/styles.css
Labels: Bugfix

#365 Release 43
  blocks/header/header.css
  blocks/header/header.js
  blocks/v2-custom-form/v2-custom-form.js
  blocks/v2-embed/v2-embed.js
  blocks/v2-truck-lineup/v2-truck-lineup.css
  blocks/v2-truck-lineup/v2-truck-lineup.js
  common/modal/modal-component.css
  icons/muted.svg
  icons/unmuted.svg
  package-lock.json
  package.json
  scripts/video-helper.js
  styles/styles.css
Labels: Ignore for release
