Repository aemsites/vg-macktrucks-com, pull requests merged in 2025-03, with the labels that each got.

#208 FR: PDP Feature Benefit Slider - V2 Icon Card variant #184
  blocks/dealer-locator/dealer-locator.js
  blocks/v2-dealer-locator/v2-dealer-locator.js
  blocks/v2-icon-cards/v2-icon-cards.css
  blocks/v2-icon-cards/v2-icon-cards.js
  common/countdown/countdown.css
  scripts/common.js
Labels: FR

#214 Release 36
  blocks/dealer-locator/dealer-locator.js
  blocks/header/header.css
  blocks/header/header.js
  blocks/v2-columns/v2-columns.css
  blocks/v2-columns/v2-columns.js
  blocks/v2-dealer-locator/v2-dealer-locator.js
  blocks/v2-hotspots/v2-hotspots.css
  blocks/v2-icon-cards/v2-icon-cards.css
  blocks/v2-icon-cards/v2-icon-cards.js
  blocks/v2-product-listing/v2-product-listing.css
  blocks/v2-product-listing/v2-product-listing.js
  common/countdown/countdown.css
  icons/new-label.svg
  package-lock.json
  package.json
  scripts/common.js
Labels: Ignore for release

#225 Bug: Recent articles block wrong links #223
  blocks/recent-articles/recent-articles.js
Labels: Bugfix

#221 FR: V2 Truck Lineup - enhancements #185
  blocks/v2-truck-lineup/v2-truck-lineup.css
  blocks/v2-truck-lineup/v2-truck-lineup.js
  scripts/scripts.js
Labels: FR

#222 FR: Countdown in hero - content displayed / restream integration (3 of 4) #154
  blocks/hero/hero.css
  blocks/v2-hero-reveal/v2-hero-reveal.css
  blocks/v2-hero-reveal/v2-hero-reveal.js
  blocks/v2-hero/v2-hero.css
  blocks/v2-hero/v2-hero.js
  blocks/v2-hotspots/v2-hotspots.css
  common/countdown/countdown.css
  common/modal/modal-component.css
  package-lock.json
  package.json
  scripts/video-helper.js
  styles/lazy-styles.css
  styles/styles.css
Labels: FR

#229 FR: V2-columns functionality for Hotspot with Tooltip #183
  blocks/dealer-locator/dealer-locator.js
  blocks/performance-specifications/performance-specifications.js
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-image-banner/v2-image-banner.css
  blocks/v2-picture-tooltips/v2-picture-tooltips.css
  blocks/v2-picture-tooltips/v2-picture-tooltips.js
  blocks/v2-recommendations/v2-recommendations.css
  blocks/v2-stories-carousel/v2-stories-carousel.css
  common/modal/modal-component.css
  placeholder.json
  scripts/common.js
  styles/lazy-styles.css
  styles/styles.css
Labels: FR
