Repository aemsites/vg-macktrucks-com, pull requests merged in 2025-08, with the labels that each got.

#410 FR: Update custom header component #219
  blocks/header/header.css
  blocks/header/header.js
Labels: FR

#406 NFR: Request for Maze Integration for Usability Testing PoC #49
  scripts/delayed.js
Labels: NFR

#408 Bug: Web version of the Dealer Locator shows incorrect distance #390
  blocks/dealer-locator/sidebar-maps.js
  blocks/v2-dealer-locator/v2-dealer-locator.css
  blocks/v2-dealer-locator/versions/default/sidebar-maps.js
  blocks/v2-dealer-locator/versions/export/sidebar-maps.js
  blocks/v2-hero/v2-hero.css
  styles/styles.css
Labels: Bugfix

#415 FR: V2 Recommendations block with video #72
  blocks/v2-recommendations/v2-recommendations.css
  blocks/v2-recommendations/v2-recommendations.js
  scripts/search-api.js
  scripts/services/magazine.service.js
  scripts/video-helper.js
Labels: FR

#412 Bug: [v2-trucks-lineup] #65
  blocks/v2-truck-lineup/v2-truck-lineup.js
Labels: Bugfix

#418 Release 47
  blocks/dealer-locator/sidebar-maps.js
  blocks/header/header.css
  blocks/header/header.js
  blocks/v2-dealer-locator/v2-dealer-locator.css
  blocks/v2-dealer-locator/versions/default/sidebar-maps.js
  blocks/v2-dealer-locator/versions/export/sidebar-maps.js
  blocks/v2-hero/v2-hero.css
  blocks/v2-pencil-promo/v2-pencil-promo.css
  blocks/v2-pencil-promo/v2-pencil-promo.js
  blocks/v2-recommendations/v2-recommendations.css
  blocks/v2-recommendations/v2-recommendations.js
  blocks/v2-truck-lineup/v2-truck-lineup.js
  package-lock.json
  package.json
  scripts/delayed.js
  scripts/search-api.js
  scripts/services/magazine.service.js
  scripts/video-helper.js
  styles/styles.css
Labels: Ignore for release

#423 Bug: Issue with km/mi toggle on V2 Dealer Locator block #311
  blocks/v2-dealer-locator/v2-dealer-locator.css
  blocks/v2-dealer-locator/versions/default/sidebar-maps.js
  blocks/v2-dealer-locator/versions/export/sidebar-maps.js
Labels: Bugfix

#427 CR: The dotted background used for the engine image is placed to the right of the image in Mobile view
  blocks/v2-columns/v2-columns.css
  blocks/v2-columns/v2-columns.js
  blocks/v2-product-listing/v2-product-listing.css
  media/dots-desktop.svg
  media/dots-mobile.svg
Labels: Change Request

#431 FR: Enhance Image quality in the V2 cards block
  blocks/v2-cards/v2-cards.css
  blocks/v2-cards/v2-cards.js
Labels: FR

#430 FR: Video capability in the V2 Cards block #399
  blocks/v2-cards/v2-cards.css
  blocks/v2-cards/v2-cards.js
Labels: FR
