Repository aemsites/vg-macktrucks-com, pull requests merged in 2025-02, with the labels that each got.

#176 Hero with video button #150
  blocks/v2-hero/v2-hero.js
Labels: Bugfix

#160 FR: "Most Recent" and "Alphabetical" order toggle - FE work #39
  blocks/v2-explore-articles/v2-explore-articles.css
  blocks/v2-explore-articles/v2-explore-articles.js
  placeholder.json
  scripts/services/magazine.service.js
Labels: FR

#171 Countdown - Contact form (2 of 4) #145
  blocks/v2-hero/v2-hero.css
  blocks/v2-hero/v2-hero.js
Labels: FR

#188 Release 34
  blocks/v2-explore-articles/v2-explore-articles.css
  blocks/v2-explore-articles/v2-explore-articles.js
  blocks/v2-hero/v2-hero.css
  blocks/v2-hero/v2-hero.js
  package-lock.json
  package.json
  placeholder.json
  scripts/services/magazine.service.js
Labels: Ignore for release

#196 FR: Navigation - Addition of an "Industry" tab section to the navigation #178
  blocks/header/header.css
Labels: FR

#195 FR: Create New Block for Marketing Cloud Account Engagement Forms - MT #168
  blocks/v2-custom-form/responses/error.js
  blocks/v2-custom-form/responses/success.js
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
  common/custom-dropdown/custom-dropdown.css
  common/custom-dropdown/custom-dropdown.js
  eslint.config.mjs
  icons/tick.svg
  placeholder.json
  scripts/common.js
  styles/styles.css
Labels: FR

#205 Release 35
  blocks/header/header.css
  blocks/v2-custom-form/responses/error.js
  blocks/v2-custom-form/responses/success.js
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
  common/custom-dropdown/custom-dropdown.css
  common/custom-dropdown/custom-dropdown.js
  eslint.config.mjs
  icons/tick.svg
  package-lock.json
  package.json
  placeholder.json
  scripts/common.js
  styles/styles.css
Labels: Ignore for release

#203 Navigation - Mack Mega Menu Change #179
  blocks/header/header.css
  blocks/header/header.js
Labels: FR
