Repository aemsites/vg-macktrucks-com, pull requests merged in 2025-04, with the labels that each got.

#234 FR: Add text content to the v2-picture-tooltips block #218
  blocks/v2-picture-tooltips/v2-picture-tooltips.css
  blocks/v2-picture-tooltips/v2-picture-tooltips.js
Labels: FR

#243 Replicate in MT Adobe changes made on VT #220
  blocks/v2-category-collage/v2-category-collage.css
  blocks/v2-category-collage/v2-category-collage.js
  blocks/v2-embed/v2-embed.css
  blocks/v2-embed/v2-embed.js
  blocks/v2-hero/v2-hero.css
  blocks/v2-hero/v2-hero.js
  blocks/v2-video/v2-video.css
  blocks/v2-video/v2-video.js
  common/modal/modal-component.css
  common/modal/modal-component.js
  package-lock.json
  package.json
  scripts/common.js
  scripts/delayed.js
  scripts/video-helper.js
  scripts/videojs/video-js.min.css
  scripts/videojs/video.min.js
  styles/styles.css
Labels: FR

#247 FR: V2 Feature Carousel - Slider variant image and content #190
  blocks/v2-feature-carousel/v2-feature-carousel.css
  blocks/v2-feature-carousel/v2-feature-carousel.js
Labels: FR

#250 V2 Embed - Stylized play button in top right corner #182
  blocks/v2-embed/v2-embed.js
Labels: FR

#252 Release 38
  blocks/header/header.css
  blocks/header/header.js
  blocks/v2-category-collage/v2-category-collage.css
  blocks/v2-category-collage/v2-category-collage.js
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-embed/v2-embed.css
  blocks/v2-embed/v2-embed.js
  blocks/v2-feature-carousel/v2-feature-carousel.css
  blocks/v2-feature-carousel/v2-feature-carousel.js
  blocks/v2-hero/v2-hero.css
  blocks/v2-hero/v2-hero.js
  blocks/v2-picture-tooltips/v2-picture-tooltips.css
  blocks/v2-picture-tooltips/v2-picture-tooltips.js
  blocks/v2-video/v2-video.css
  blocks/v2-video/v2-video.js
  common/custom-dropdown/custom-dropdown.css
  common/modal/modal-component.css
  common/modal/modal-component.js
  package-lock.json
  package.json
  placeholder.json
  scripts/common.js
  scripts/delayed.js
  scripts/video-helper.js
  scripts/videojs/video-js.min.css
  scripts/videojs/video.min.js
  styles/styles.css
  test/scripts/video-helper.test.js
Labels: Ignore for release

#245 V2 Columns - Video launcher variant #189
  blocks/v2-columns/v2-columns.css
  blocks/v2-columns/v2-columns.js
  styles/styles.css
Labels: FR

#261 FR: V2 Custom Form placeholder temporarily visible in dropdown #239
  blocks/v2-custom-form/v2-custom-form.js
  common/custom-dropdown/custom-dropdown.css
  common/custom-dropdown/custom-dropdown.js
  package.json
  styles/styles.css
Labels: FR

#262 Task: Add Check box to forms #253
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
Labels: FR

#266 Custom playback button not working on iOS #265
  scripts/video-helper.js
Labels: Bugfix

#271 Add failsafe code for header and footer #270
  blocks/footer/footer.js
  blocks/header/header.js
  styles/styles.css
Labels: Bugfix

#249 NFR: Filter Functionality for Dynamically Updating Pencil Promo Block #93
  blocks/v2-pencil-promo/v2-pencil-promo.css
  blocks/v2-pencil-promo/v2-pencil-promo.js
  blocks/v2-product-listing/v2-product-listing.js
Labels: NFR

#279 MT video not playing on iOS #274
  blocks/header/header.js
  common/modal/modal-component.css
Labels: Bugfix

#272 FR: Increase Font Size in Mack-News Template #73
  package.json
  templates/mack-news/mack-news.css
Labels: FR

#277 V2 Images Grid – Improve Mobile Captions with Pop-Up Display #61
  blocks/v2-images-grid/v2-images-grid.css
  blocks/v2-images-grid/v2-images-grid.js
  icons/info.svg
  placeholder.json
Labels: FR

#284 Release 39
  blocks/v2-images-grid/v2-images-grid.css
  blocks/v2-images-grid/v2-images-grid.js
  blocks/v2-pencil-promo/v2-pencil-promo.css
  blocks/v2-pencil-promo/v2-pencil-promo.js
  blocks/v2-product-listing/v2-product-listing.js
  icons/info.svg
  package-lock.json
  package.json
  placeholder.json
  scripts/video-helper.js
  templates/mack-news/mack-news.css
Labels: Ignore for release

#289 Bug: V2 form block has white text on white background in the dropdowns #269
  common/custom-dropdown/custom-dropdown.css
Labels: bug

#288 Improvement: Hiding the "Let's talk" verbiage after a successful form submission #273
  blocks/v2-custom-form/v2-custom-form.js
Labels: FR

#294 FR: MCAE form fields validations #260
  blocks/v2-custom-form/v2-custom-form.js
Labels: FR

#296 Bug: Magazines on the Mack Trucks disappeared for the New Zealand site #292
  blocks/explore-articles/explore-articles.js
  package.json
  scripts/search-api.js
  scripts/services/magazine.service.js
Labels: bug
